import { z } from 'zod';

export const WORKSPACE_MIRROR_SCHEMA_VERSION = 1;
export const WORKSPACE_MIRROR_PROTOCOL_VERSION = 2;
export const WORKSPACE_MIRROR_SUBPROTOCOL = 'enso-mirror.v2';
export const WORKSPACE_MIRROR_MAX_SNAPSHOT_CHUNK_BYTES = 1024 * 1024;
export const WORKSPACE_MIRROR_MAX_SNAPSHOT_BYTES = 64 * 1024 * 1024;
export const WORKSPACE_MIRROR_MAX_RESOURCE_BYTES = 10 * 1024 * 1024;
export const WORKSPACE_MIRROR_MAX_RESOURCE_CHUNK_BYTES = 512 * 1024;
export const WORKSPACE_MIRROR_MAX_RESOURCE_BASE64_LENGTH =
  Math.ceil((WORKSPACE_MIRROR_MAX_RESOURCE_BYTES * 4) / 3) + 4;
/** Opaque URI returned to remote renderers for host-owned attachments. */
export const WORKSPACE_RESOURCE_URI_PREFIX = 'enso-resource://';

/**
 * Resource ids are generated by the host and deliberately use a URL-safe
 * alphabet. Keeping the validation here lets renderer URL conversion and the
 * main-process protocol handler agree without ever treating an opaque id as
 * a filesystem path.
 */
export function isWorkspaceResourceId(value: string): boolean {
  return /^[A-Za-z0-9._:-]{1,256}$/.test(value);
}

export function workspaceResourceIdFromUri(value: string): string | null {
  if (!value.toLowerCase().startsWith(WORKSPACE_RESOURCE_URI_PREFIX)) return null;
  const resourceId = value.slice(WORKSPACE_RESOURCE_URI_PREFIX.length);
  return isWorkspaceResourceId(resourceId) ? resourceId : null;
}

const MAX_ID_LENGTH = 256;
const MAX_NAME_LENGTH = 1024;
const MAX_PATH_LENGTH = 32 * 1024;
const MAX_TEXT_LENGTH = 16 * 1024 * 1024;
const MAX_COLLECTION_SIZE = 10_000;
const MAX_JSON_DEPTH = 32;
const MAX_JSON_ENTRIES = 10_000;

const boundedId = z.string().min(1).max(MAX_ID_LENGTH);
const boundedName = z.string().max(MAX_NAME_LENGTH);
const boundedPath = z.string().min(1).max(MAX_PATH_LENGTH);
const boundedText = z.string().max(MAX_TEXT_LENGTH);
const nullableId = boundedId.nullable();
const safeInteger = z.number().int().nonnegative().max(Number.MAX_SAFE_INTEGER);
const positiveSafeInteger = z.number().int().positive().max(Number.MAX_SAFE_INTEGER);
const timestamp = safeInteger;
const sha256 = z.string().regex(/^[a-f0-9]{64}$/);

export const WorkspaceEntityIdSchema = boundedId;
export const WorkspaceHostIdSchema = boundedId;
export const WorkspaceSceneIdSchema = boundedId;
export const WorkspaceHostEpochSchema = z.string().uuid();
export const WorkspaceRevisionSchema = safeInteger;
export const WorkspaceSequenceSchema = safeInteger;
export const WorkspaceSha256Schema = sha256;

export type WorkspaceEntityId = z.infer<typeof WorkspaceEntityIdSchema>;
export type WorkspaceHostId = z.infer<typeof WorkspaceHostIdSchema>;
export type WorkspaceSceneId = z.infer<typeof WorkspaceSceneIdSchema>;
export type WorkspaceHostEpoch = z.infer<typeof WorkspaceHostEpochSchema>;
export type WorkspaceRevision = z.infer<typeof WorkspaceRevisionSchema>;

function boundedRecord<Value extends z.ZodType>(valueSchema: Value) {
  return z.record(boundedId, valueSchema).superRefine((value, context) => {
    if (Object.keys(value).length > MAX_COLLECTION_SIZE) {
      context.addIssue({
        code: 'too_big',
        maximum: MAX_COLLECTION_SIZE,
        origin: 'object',
        inclusive: true,
        message: `Record cannot contain more than ${MAX_COLLECTION_SIZE} entries`,
      });
    }
  });
}

const idArray = z.array(boundedId).max(MAX_COLLECTION_SIZE);

export const WorkspacePanelIdSchema = z.enum([
  'chat',
  'file',
  'terminal',
  'source-control',
  'todo',
]);

export type WorkspacePanelId = z.infer<typeof WorkspacePanelIdSchema>;

export const RepositoryGroupSceneSchema = z.strictObject({
  id: boundedId,
  name: boundedName,
  emoji: z.string().max(32),
  color: z.string().min(1).max(128),
  order: safeInteger,
});

export type RepositoryGroupScene = z.infer<typeof RepositoryGroupSceneSchema>;

export const RepositorySettingsSceneSchema = z.strictObject({
  autoInitWorktree: z.boolean(),
  initScript: z.string().max(256 * 1024),
  hidden: z.boolean(),
});

export type RepositorySettingsScene = z.infer<typeof RepositorySettingsSceneSchema>;

export const RepositorySceneSchema = z.strictObject({
  id: boundedId,
  path: boundedPath,
  name: boundedName,
  groupId: nullableId,
  order: safeInteger,
  settings: RepositorySettingsSceneSchema,
});

export type RepositoryScene = z.infer<typeof RepositorySceneSchema>;

export const WorktreeSceneSchema = z.strictObject({
  id: boundedId,
  repositoryId: boundedId,
  path: boundedPath,
  name: boundedName,
  branch: z.string().max(MAX_NAME_LENGTH).nullable(),
  order: safeInteger,
  isMain: z.boolean(),
});

export type WorktreeScene = z.infer<typeof WorktreeSceneSchema>;

export const WorkspaceCatalogSceneSchema = z.strictObject({
  groups: boundedRecord(RepositoryGroupSceneSchema),
  repositories: boundedRecord(RepositorySceneSchema),
  worktrees: boundedRecord(WorktreeSceneSchema),
});

export type WorkspaceCatalogScene = z.infer<typeof WorkspaceCatalogSceneSchema>;

export const NavigationSceneSchema = z.strictObject({
  selectedRepositoryId: nullableId,
  activeGroupId: nullableId,
  activeWorktreeId: nullableId,
  activePrimaryPanel: WorkspacePanelIdSchema,
  activePanelByWorktree: boundedRecord(WorkspacePanelIdSchema),
  panelOrderByWorktree: boundedRecord(z.array(WorkspacePanelIdSchema).max(16)),
});

export type NavigationScene = z.infer<typeof NavigationSceneSchema>;

export const EditorTabSceneSchema = z.strictObject({
  id: boundedId,
  path: boundedPath,
  title: boundedName,
  order: safeInteger,
  encoding: z.string().min(1).max(64),
  isUnsupported: z.boolean(),
});

export type EditorTabScene = z.infer<typeof EditorTabSceneSchema>;

export const EditorBufferSceneSchema = z
  .strictObject({
    path: boundedPath,
    content: boundedText.optional(),
    isDirty: z.boolean(),
    version: safeInteger,
    hasExternalChange: z.boolean(),
    externalContent: boundedText.optional(),
  })
  .superRefine((value, context) => {
    if (value.isDirty && value.content === undefined) {
      context.addIssue({
        code: 'custom',
        path: ['content'],
        message: 'Dirty buffers must include their current content',
      });
    }
    if (value.hasExternalChange && value.externalContent === undefined) {
      context.addIssue({
        code: 'custom',
        path: ['externalContent'],
        message: 'External conflicts must include the authoritative external content',
      });
    }
  });

export type EditorBufferScene = z.infer<typeof EditorBufferSceneSchema>;

export const EditorSceneSchema = z.strictObject({
  tabs: z.array(EditorTabSceneSchema).max(MAX_COLLECTION_SIZE),
  activeFile: boundedPath.nullable(),
  buffers: z.record(boundedPath, EditorBufferSceneSchema).superRefine((value, context) => {
    if (Object.keys(value).length > MAX_COLLECTION_SIZE) {
      context.addIssue({
        code: 'too_big',
        maximum: MAX_COLLECTION_SIZE,
        origin: 'object',
        inclusive: true,
        message: `Editor cannot contain more than ${MAX_COLLECTION_SIZE} buffers`,
      });
    }
  }),
});

export type EditorScene = z.infer<typeof EditorSceneSchema>;

export const WorkspaceResourceReferenceSchema = z.strictObject({
  id: boundedId,
  displayName: boundedName,
  mime: z.string().min(1).max(256),
  size: safeInteger,
  checksum: sha256,
});

export type WorkspaceResourceReference = z.infer<typeof WorkspaceResourceReferenceSchema>;

export const ResourceUploadBeginFrameSchema = z
  .strictObject({
    t: z.literal('resource.upload.begin'),
    requestId: boundedId,
    uploadId: boundedId,
    displayName: z.string().min(1).max(512),
    mime: z.string().min(1).max(256).optional(),
    totalBytes: safeInteger,
    totalChunks: positiveSafeInteger,
    checksum: sha256,
  })
  .superRefine((value, context) => {
    if (value.totalBytes > WORKSPACE_MIRROR_MAX_RESOURCE_BYTES) {
      context.addIssue({
        code: 'too_big',
        maximum: WORKSPACE_MIRROR_MAX_RESOURCE_BYTES,
        origin: 'number',
        inclusive: true,
        path: ['totalBytes'],
        message: 'Resource upload exceeds the size limit',
      });
    }
    const expectedChunks = Math.max(
      1,
      Math.ceil(value.totalBytes / WORKSPACE_MIRROR_MAX_RESOURCE_CHUNK_BYTES)
    );
    if (value.totalChunks !== expectedChunks) {
      context.addIssue({
        code: 'custom',
        path: ['totalChunks'],
        message: 'Resource upload chunk count does not match total bytes',
      });
    }
  });

export const ResourceUploadChunkFrameSchema = z.strictObject({
  t: z.literal('resource.upload.chunk'),
  uploadId: boundedId,
  index: safeInteger,
  data: z
    .string()
    .max(Math.ceil(WORKSPACE_MIRROR_MAX_RESOURCE_CHUNK_BYTES / 3) * 4)
    .regex(/^[A-Za-z0-9+/]*={0,2}$/),
  checksum: sha256,
});

export const ResourceUploadEndFrameSchema = z.strictObject({
  t: z.literal('resource.upload.end'),
  uploadId: boundedId,
  totalChunks: positiveSafeInteger,
  checksum: sha256,
});

export const ResourceUploadResultFrameSchema = z.strictObject({
  t: z.literal('resource.upload.result'),
  requestId: boundedId,
  uploadId: boundedId,
  reference: WorkspaceResourceReferenceSchema,
});

export type ResourceUploadBeginFrame = z.infer<typeof ResourceUploadBeginFrameSchema>;
export type ResourceUploadChunkFrame = z.infer<typeof ResourceUploadChunkFrameSchema>;
export type ResourceUploadEndFrame = z.infer<typeof ResourceUploadEndFrameSchema>;
export type ResourceUploadResultFrame = z.infer<typeof ResourceUploadResultFrameSchema>;

export const WorkspaceResourceUploadSchema = z.strictObject({
  displayName: z.string().min(1).max(512),
  mime: z.string().min(1).max(256).optional(),
  data: z.string().max(WORKSPACE_MIRROR_MAX_RESOURCE_BASE64_LENGTH),
});

export type WorkspaceResourceUpload = z.infer<typeof WorkspaceResourceUploadSchema>;

export const AgentInputDraftSchema = z.strictObject({
  text: z.string().max(1024 * 1024),
  resources: z.array(WorkspaceResourceReferenceSchema).max(128),
});

export type AgentInputDraft = z.infer<typeof AgentInputDraftSchema>;

export const AgentTaskSceneSchema = z.strictObject({
  id: boundedId,
  status: z.enum(['idle', 'running', 'waiting', 'completed', 'paused', 'error']),
  description: z.string().max(16 * 1024),
  waitingReason: z
    .string()
    .max(16 * 1024)
    .nullable(),
  startedAt: timestamp.nullable(),
  completedAt: timestamp.nullable(),
});

export type AgentTaskScene = z.infer<typeof AgentTaskSceneSchema>;

export const AgentSessionSceneSchema = z.strictObject({
  id: boundedId,
  providerSessionId: nullableId.default(null),
  generation: positiveSafeInteger,
  agentId: boundedId,
  name: boundedName,
  repositoryId: nullableId,
  worktreeId: nullableId,
  terminalSessionId: nullableId,
  environment: z.enum(['native', 'hapi', 'happy']),
  initialized: z.boolean(),
  activated: z.boolean(),
  displayOrder: safeInteger,
  runtimeState: z.enum(['idle', 'outputting', 'unread']),
  status: z.enum(['idle', 'running', 'waiting', 'completed', 'paused', 'error']),
  waitingReason: z
    .string()
    .max(16 * 1024)
    .nullable(),
  draft: AgentInputDraftSchema,
  task: AgentTaskSceneSchema.nullable(),
});

export type AgentSessionScene = z.infer<typeof AgentSessionSceneSchema>;

export const AgentGroupSceneSchema = z.strictObject({
  id: boundedId,
  worktreeId: boundedId,
  layout: z.enum(['tabs', 'horizontal', 'vertical']),
  sessionIds: idArray,
  activeSessionId: nullableId,
  order: safeInteger,
});

export type AgentGroupScene = z.infer<typeof AgentGroupSceneSchema>;

export const AgentSceneSchema = z.strictObject({
  sessions: boundedRecord(AgentSessionSceneSchema),
  groups: boundedRecord(AgentGroupSceneSchema),
  activeSessionByWorktree: boundedRecord(nullableId),
});

export type AgentScene = z.infer<typeof AgentSceneSchema>;

export const TerminalSessionSceneSchema = z.strictObject({
  id: boundedId,
  generation: positiveSafeInteger,
  repositoryId: nullableId,
  worktreeId: nullableId,
  title: boundedName,
  cwd: boundedPath,
  groupId: nullableId,
  order: safeInteger,
  processState: z.enum(['starting', 'running', 'exited', 'terminated', 'unknown']),
  exitCode: z.number().int().nullable(),
});

export type TerminalSessionScene = z.infer<typeof TerminalSessionSceneSchema>;

export const TerminalGroupSceneSchema = z.strictObject({
  id: boundedId,
  worktreeId: boundedId,
  layout: z.enum(['tabs', 'horizontal', 'vertical']),
  sessionIds: idArray,
  activeSessionId: nullableId,
  order: safeInteger,
});

export type TerminalGroupScene = z.infer<typeof TerminalGroupSceneSchema>;

export const TerminalSceneSchema = z.strictObject({
  sessions: boundedRecord(TerminalSessionSceneSchema),
  groups: boundedRecord(TerminalGroupSceneSchema),
  activeSessionByWorktree: boundedRecord(nullableId),
  quickSessionByWorktree: boundedRecord(boundedId),
});

export type TerminalScene = z.infer<typeof TerminalSceneSchema>;

export const TodoTaskSceneSchema = z.strictObject({
  id: boundedId,
  title: z.string().max(16 * 1024),
  description: z.string().max(256 * 1024),
  priority: z.enum(['low', 'medium', 'high']),
  status: z.enum(['todo', 'in-progress', 'done']),
  createdAt: timestamp,
  updatedAt: timestamp,
  order: safeInteger,
  sessionId: nullableId,
});

export type TodoTaskScene = z.infer<typeof TodoTaskSceneSchema>;

export const TodoAutoExecutionSceneSchema = z.strictObject({
  running: z.boolean(),
  queue: idArray,
  currentTaskId: nullableId,
  currentSessionId: nullableId,
});

export type TodoAutoExecutionScene = z.infer<typeof TodoAutoExecutionSceneSchema>;

export const TodoBoardSceneSchema = z.strictObject({
  tasks: boundedRecord(TodoTaskSceneSchema),
  autoExecution: TodoAutoExecutionSceneSchema,
});

export type TodoBoardScene = z.infer<typeof TodoBoardSceneSchema>;

export const TodoSceneSchema = z.strictObject({
  boardsByRepository: boundedRecord(TodoBoardSceneSchema),
});

export type TodoScene = z.infer<typeof TodoSceneSchema>;

export const SemanticSelectionSceneSchema = z.strictObject({
  selectedFileByWorktree: z.record(boundedId, boundedPath.nullable()),
  selectedDiffByWorktree: z.record(boundedId, boundedPath.nullable()),
  selectedTaskByRepository: boundedRecord(nullableId),
});

export type SemanticSelectionScene = z.infer<typeof SemanticSelectionSceneSchema>;

export const WorkspaceResourceDomainSchema = z.enum([
  'file-tree',
  'git-status',
  'diff',
  'search',
  'todo',
  'agent',
  'terminal',
]);

export const WorkspaceResourceInvalidationSchema = z.strictObject({
  resourceKey: z.string().min(1).max(1024),
  domain: WorkspaceResourceDomainSchema,
  entityId: nullableId,
  generation: positiveSafeInteger,
  reason: z.enum(['changed', 'deleted', 'renamed', 'reset']),
});

export type WorkspaceResourceInvalidation = z.infer<typeof WorkspaceResourceInvalidationSchema>;

export const WorkspaceResourceSceneSchema = z.strictObject({
  invalidations: z
    .record(z.string().min(1).max(1024), WorkspaceResourceInvalidationSchema)
    .superRefine((value, context) => {
      if (Object.keys(value).length > MAX_COLLECTION_SIZE) {
        context.addIssue({
          code: 'too_big',
          maximum: MAX_COLLECTION_SIZE,
          origin: 'object',
          inclusive: true,
          message: `Resource scene cannot contain more than ${MAX_COLLECTION_SIZE} entries`,
        });
      }
    }),
});

export type WorkspaceResourceScene = z.infer<typeof WorkspaceResourceSceneSchema>;

export const WorkspaceSceneSnapshotSchema = z.strictObject({
  schemaVersion: z.literal(WORKSPACE_MIRROR_SCHEMA_VERSION),
  hostId: WorkspaceHostIdSchema,
  sceneId: WorkspaceSceneIdSchema,
  hostEpoch: WorkspaceHostEpochSchema,
  revision: WorkspaceRevisionSchema,
  catalog: WorkspaceCatalogSceneSchema,
  navigation: NavigationSceneSchema,
  editors: boundedRecord(EditorSceneSchema),
  agents: AgentSceneSchema,
  terminals: TerminalSceneSchema,
  todos: TodoSceneSchema,
  selections: SemanticSelectionSceneSchema,
  resources: WorkspaceResourceSceneSchema,
});

export type WorkspaceSceneSnapshot = z.infer<typeof WorkspaceSceneSnapshotSchema>;

export interface WorkspaceSceneIdentity {
  hostId: WorkspaceHostId;
  sceneId: WorkspaceSceneId;
  hostEpoch: WorkspaceHostEpoch;
}

export function createEmptyWorkspaceSceneSnapshot(
  identity: WorkspaceSceneIdentity
): WorkspaceSceneSnapshot {
  return WorkspaceSceneSnapshotSchema.parse({
    schemaVersion: WORKSPACE_MIRROR_SCHEMA_VERSION,
    ...identity,
    revision: 0,
    catalog: { groups: {}, repositories: {}, worktrees: {} },
    navigation: {
      selectedRepositoryId: null,
      activeGroupId: null,
      activeWorktreeId: null,
      activePrimaryPanel: 'chat',
      activePanelByWorktree: {},
      panelOrderByWorktree: {},
    },
    editors: {},
    agents: { sessions: {}, groups: {}, activeSessionByWorktree: {} },
    terminals: {
      sessions: {},
      groups: {},
      activeSessionByWorktree: {},
      quickSessionByWorktree: {},
    },
    todos: { boardsByRepository: {} },
    selections: {
      selectedFileByWorktree: {},
      selectedDiffByWorktree: {},
      selectedTaskByRepository: {},
    },
    resources: { invalidations: {} },
  });
}

const CatalogReplaceMutationSchema = z.strictObject({
  kind: z.literal('catalog.replace'),
  payload: z.strictObject({ catalog: WorkspaceCatalogSceneSchema }),
});

const SceneReplacePayloadSchema = z.strictObject({
  catalog: WorkspaceCatalogSceneSchema,
  navigation: NavigationSceneSchema,
  editors: boundedRecord(EditorSceneSchema),
  agents: AgentSceneSchema,
  terminals: TerminalSceneSchema,
  todos: TodoSceneSchema,
  selections: SemanticSelectionSceneSchema,
});

const SceneReplaceMutationSchema = z.strictObject({
  kind: z.literal('scene.replace'),
  payload: SceneReplacePayloadSchema,
});

const NavigationReplaceMutationSchema = z.strictObject({
  kind: z.literal('navigation.replace'),
  payload: z.strictObject({ navigation: NavigationSceneSchema }),
});

const EditorReplaceMutationSchema = z.strictObject({
  kind: z.literal('editor.replace'),
  payload: z.strictObject({ worktreeId: boundedId, editor: EditorSceneSchema }),
});

const EditorRemoveMutationSchema = z.strictObject({
  kind: z.literal('editor.remove'),
  payload: z.strictObject({ worktreeId: boundedId }),
});

export const EditorBufferUpdatePayloadSchema = z
  .strictObject({
    worktreeId: boundedId,
    path: boundedPath,
    baseVersion: safeInteger,
    nextVersion: positiveSafeInteger,
    content: boundedText.optional(),
    isDirty: z.boolean(),
    encoding: z.string().min(1).max(64).optional(),
    hasExternalChange: z.boolean(),
    externalContent: boundedText.optional(),
  })
  .superRefine((value, context) => {
    if (value.nextVersion !== value.baseVersion + 1) {
      context.addIssue({
        code: 'custom',
        path: ['nextVersion'],
        message: 'nextVersion must equal baseVersion + 1',
      });
    }
    if (value.isDirty && value.content === undefined) {
      context.addIssue({
        code: 'custom',
        path: ['content'],
        message: 'Dirty buffer updates must include current content',
      });
    }
    if (value.hasExternalChange && value.externalContent === undefined) {
      context.addIssue({
        code: 'custom',
        path: ['externalContent'],
        message: 'External conflicts must include authoritative external content',
      });
    }
  });

export type EditorBufferUpdatePayload = z.infer<typeof EditorBufferUpdatePayloadSchema>;

const EditorBufferUpdateMutationSchema = z.strictObject({
  kind: z.literal('editor.buffer.update'),
  payload: EditorBufferUpdatePayloadSchema,
});

const AgentsReplaceMutationSchema = z.strictObject({
  kind: z.literal('agents.replace'),
  payload: z.strictObject({ agents: AgentSceneSchema }),
});

const TerminalsReplaceMutationSchema = z.strictObject({
  kind: z.literal('terminals.replace'),
  payload: z.strictObject({ terminals: TerminalSceneSchema }),
});

const TodosReplaceMutationSchema = z.strictObject({
  kind: z.literal('todos.replace'),
  payload: z.strictObject({ todos: TodoSceneSchema }),
});

const SelectionsReplaceMutationSchema = z.strictObject({
  kind: z.literal('selections.replace'),
  payload: z.strictObject({ selections: SemanticSelectionSceneSchema }),
});

const ResourcesInvalidateMutationSchema = z.strictObject({
  kind: z.literal('resources.invalidate'),
  payload: WorkspaceResourceInvalidationSchema,
});

const workspaceMutationSchemas = [
  SceneReplaceMutationSchema,
  CatalogReplaceMutationSchema,
  NavigationReplaceMutationSchema,
  EditorReplaceMutationSchema,
  EditorRemoveMutationSchema,
  EditorBufferUpdateMutationSchema,
  AgentsReplaceMutationSchema,
  TerminalsReplaceMutationSchema,
  TodosReplaceMutationSchema,
  SelectionsReplaceMutationSchema,
  ResourcesInvalidateMutationSchema,
] as const;

export const WorkspaceSceneMutationSchema = z.discriminatedUnion('kind', workspaceMutationSchemas);

export type WorkspaceSceneMutation = z.infer<typeof WorkspaceSceneMutationSchema>;

const intentEnvelope = {
  t: z.literal('state.intent'),
  operationId: boundedId,
  clientSeq: positiveSafeInteger,
  baseRevision: WorkspaceRevisionSchema,
};

export const WorkspaceSceneIntentSchema = z.discriminatedUnion('kind', [
  SceneReplaceMutationSchema.extend(intentEnvelope),
  CatalogReplaceMutationSchema.extend(intentEnvelope),
  NavigationReplaceMutationSchema.extend(intentEnvelope),
  EditorReplaceMutationSchema.extend(intentEnvelope),
  EditorRemoveMutationSchema.extend(intentEnvelope),
  EditorBufferUpdateMutationSchema.extend(intentEnvelope),
  AgentsReplaceMutationSchema.extend(intentEnvelope),
  TerminalsReplaceMutationSchema.extend(intentEnvelope),
  TodosReplaceMutationSchema.extend(intentEnvelope),
  SelectionsReplaceMutationSchema.extend(intentEnvelope),
  ResourcesInvalidateMutationSchema.extend(intentEnvelope),
]);

export type WorkspaceSceneIntent = z.infer<typeof WorkspaceSceneIntentSchema>;

export const WorkspaceEventOriginSchema = z.strictObject({
  source: z.enum(['client', 'host', 'migration', 'reconcile']),
  clientId: nullableId,
  deviceId: nullableId,
  operationId: nullableId,
});

export type WorkspaceEventOrigin = z.infer<typeof WorkspaceEventOriginSchema>;

const eventEnvelope = {
  t: z.literal('state.event'),
  hostEpoch: WorkspaceHostEpochSchema,
  sceneId: WorkspaceSceneIdSchema,
  revision: positiveSafeInteger,
  origin: WorkspaceEventOriginSchema,
};

export const WorkspaceSceneEventSchema = z.discriminatedUnion('kind', [
  SceneReplaceMutationSchema.extend(eventEnvelope),
  CatalogReplaceMutationSchema.extend(eventEnvelope),
  NavigationReplaceMutationSchema.extend(eventEnvelope),
  EditorReplaceMutationSchema.extend(eventEnvelope),
  EditorRemoveMutationSchema.extend(eventEnvelope),
  EditorBufferUpdateMutationSchema.extend(eventEnvelope),
  AgentsReplaceMutationSchema.extend(eventEnvelope),
  TerminalsReplaceMutationSchema.extend(eventEnvelope),
  TodosReplaceMutationSchema.extend(eventEnvelope),
  SelectionsReplaceMutationSchema.extend(eventEnvelope),
  ResourcesInvalidateMutationSchema.extend(eventEnvelope),
]);

export type WorkspaceSceneEvent = z.infer<typeof WorkspaceSceneEventSchema>;

export const WorkspaceResumeCursorSchema = z.strictObject({
  hostEpoch: WorkspaceHostEpochSchema,
  sceneId: WorkspaceSceneIdSchema,
  revision: WorkspaceRevisionSchema,
});

export type WorkspaceResumeCursor = z.infer<typeof WorkspaceResumeCursorSchema>;

export const ControllerLeaseSchema = z.strictObject({
  leaseId: boundedId,
  holderDeviceId: boundedId,
  holderClientId: boundedId,
  acquiredAt: timestamp,
  expiresAt: timestamp,
  graceUntil: timestamp.nullable(),
  coordSeq: positiveSafeInteger,
});

export type ControllerLease = z.infer<typeof ControllerLeaseSchema>;

export const WorkspaceMirrorScopeSchema = z.enum(['mirror.read', 'mirror.control']);
export type WorkspaceMirrorScope = z.infer<typeof WorkspaceMirrorScopeSchema>;

export const WorkspaceMirrorCapabilitySchema = z.enum([
  'scene.snapshot',
  'scene.replay',
  'scene.intent',
  'control.lease',
  'terminal.stream',
  'agent.stream',
  'resource.transfer',
  'todo.mirror',
]);

export type WorkspaceMirrorCapability = z.infer<typeof WorkspaceMirrorCapabilitySchema>;

export const WorkspaceSyncPhaseSchema = z.enum([
  'disconnected',
  'bootstrapping',
  'syncing',
  'live',
  'resyncing',
  'stale',
]);

export type WorkspaceSyncPhase = z.infer<typeof WorkspaceSyncPhaseSchema>;

export const WorkspaceMirrorErrorCodeSchema = z.enum([
  'INVALID_FRAME',
  'UNAUTHORIZED',
  'FORBIDDEN',
  'CONFLICT',
  'STALE_EPOCH',
  'REVISION_GAP',
  'RESYNC_REQUIRED',
  'LEASE_REQUIRED',
  'LEASE_EXPIRED',
  'NOT_FOUND',
  'UNKNOWN_OPERATION',
  'UNKNOWN',
  'RATE_LIMITED',
  'SNAPSHOT_TOO_LARGE',
  'CHUNK_INVALID',
  'RESOURCE_LIMIT',
  'BOOTSTRAPPING',
  'INTERNAL',
]);

export type WorkspaceMirrorErrorCode = z.infer<typeof WorkspaceMirrorErrorCodeSchema>;

export const WorkspaceMirrorErrorDetailsSchema = z.strictObject({
  expectedRevision: WorkspaceRevisionSchema.optional(),
  actualRevision: WorkspaceRevisionSchema.optional(),
  expectedHostEpoch: WorkspaceHostEpochSchema.optional(),
  actualHostEpoch: WorkspaceHostEpochSchema.optional(),
  leaseId: boundedId.optional(),
  resyncReason: z
    .enum(['retention-floor', 'epoch-changed', 'revision-gap', 'checksum', 'overflow', 'bootstrap'])
    .optional(),
});

export type WorkspaceMirrorErrorDetails = z.infer<typeof WorkspaceMirrorErrorDetailsSchema>;

export const WorkspaceMirrorErrorSchema = z.strictObject({
  code: WorkspaceMirrorErrorCodeSchema,
  message: z.string().min(1).max(512),
  retryable: z.boolean(),
  details: WorkspaceMirrorErrorDetailsSchema.optional(),
});

export type WorkspaceMirrorError = z.infer<typeof WorkspaceMirrorErrorSchema>;

export type JsonPrimitive = null | boolean | number | string;
export type JsonValue = JsonPrimitive | JsonValue[] | { [key: string]: JsonValue };

function isBoundedJsonValue(value: unknown, depth = 0, entryBudget = { value: 0 }): boolean {
  if (depth > MAX_JSON_DEPTH) {
    return false;
  }
  if (
    value === null ||
    typeof value === 'boolean' ||
    typeof value === 'string' ||
    (typeof value === 'number' && Number.isFinite(value))
  ) {
    return typeof value !== 'string' || value.length <= MAX_TEXT_LENGTH;
  }
  if (Array.isArray(value)) {
    if (value.length > MAX_JSON_ENTRIES) {
      return false;
    }
    entryBudget.value += value.length;
    return (
      entryBudget.value <= MAX_JSON_ENTRIES &&
      value.every((item) => isBoundedJsonValue(item, depth + 1, entryBudget))
    );
  }
  if (typeof value !== 'object') {
    return false;
  }
  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) {
    return false;
  }
  const entries = Object.entries(value);
  entryBudget.value += entries.length;
  return (
    entries.length <= MAX_JSON_ENTRIES &&
    entryBudget.value <= MAX_JSON_ENTRIES &&
    entries.every(
      ([key, item]) =>
        key.length <= MAX_NAME_LENGTH && isBoundedJsonValue(item, depth + 1, entryBudget)
    )
  );
}

export const JsonValueSchema = z.custom<JsonValue>(
  (value) => isBoundedJsonValue(value),
  'Expected a bounded JSON value'
);

export const StateSubscribeFrameSchema = z.strictObject({
  t: z.literal('state.subscribe'),
  requestId: boundedId,
  mode: z.enum(['auto', 'snapshot', 'resume']),
  cursor: WorkspaceResumeCursorSchema.nullable(),
});

export type StateSubscribeFrame = z.infer<typeof StateSubscribeFrameSchema>;

export const StateSnapshotBeginFrameSchema = z
  .strictObject({
    t: z.literal('state.snapshot.begin'),
    requestId: boundedId,
    snapshotId: boundedId,
    hostEpoch: WorkspaceHostEpochSchema,
    sceneId: WorkspaceSceneIdSchema,
    snapshotRevision: WorkspaceRevisionSchema,
    schemaVersion: z.literal(WORKSPACE_MIRROR_SCHEMA_VERSION),
    totalChunks: positiveSafeInteger,
    totalBytes: safeInteger,
    checksum: sha256,
  })
  .superRefine((value, context) => {
    if (value.totalBytes > WORKSPACE_MIRROR_MAX_SNAPSHOT_BYTES) {
      context.addIssue({
        code: 'too_big',
        maximum: WORKSPACE_MIRROR_MAX_SNAPSHOT_BYTES,
        origin: 'number',
        inclusive: true,
        path: ['totalBytes'],
        message: 'Snapshot exceeds the logical size limit',
      });
    }
    const expectedChunks = Math.max(
      1,
      Math.ceil(value.totalBytes / WORKSPACE_MIRROR_MAX_SNAPSHOT_CHUNK_BYTES)
    );
    if (value.totalChunks !== expectedChunks) {
      context.addIssue({
        code: 'custom',
        path: ['totalChunks'],
        message: 'Snapshot chunk count does not match total bytes',
      });
    }
  });

export type StateSnapshotBeginFrame = z.infer<typeof StateSnapshotBeginFrameSchema>;

const maxEncodedSnapshotChunkLength = Math.ceil(WORKSPACE_MIRROR_MAX_SNAPSHOT_CHUNK_BYTES / 3) * 4;

export const StateSnapshotChunkFrameSchema = z.strictObject({
  t: z.literal('state.snapshot.chunk'),
  snapshotId: boundedId,
  index: safeInteger,
  data: z
    .string()
    .min(1)
    .max(maxEncodedSnapshotChunkLength)
    .regex(/^[A-Za-z0-9+/]*={0,2}$/),
  checksum: sha256,
});

export type StateSnapshotChunkFrame = z.infer<typeof StateSnapshotChunkFrameSchema>;

export const StateSnapshotEndFrameSchema = z.strictObject({
  t: z.literal('state.snapshot.end'),
  snapshotId: boundedId,
  totalChunks: positiveSafeInteger,
  checksum: sha256,
});

export type StateSnapshotEndFrame = z.infer<typeof StateSnapshotEndFrameSchema>;

export const StateReplayFrameSchema = z
  .strictObject({
    t: z.literal('state.replay'),
    hostEpoch: WorkspaceHostEpochSchema,
    sceneId: WorkspaceSceneIdSchema,
    fromRevision: positiveSafeInteger,
    toRevision: positiveSafeInteger,
    events: z.array(WorkspaceSceneEventSchema).max(MAX_COLLECTION_SIZE),
  })
  .superRefine((value, context) => {
    if (value.toRevision < value.fromRevision) {
      context.addIssue({
        code: 'custom',
        path: ['toRevision'],
        message: 'toRevision cannot be less than fromRevision',
      });
    }
    if (value.events.length !== value.toRevision - value.fromRevision + 1) {
      context.addIssue({
        code: 'custom',
        path: ['events'],
        message: 'Replay must contain one event for each revision in its range',
      });
    }
    for (const [index, event] of value.events.entries()) {
      if (event.revision !== value.fromRevision + index) {
        context.addIssue({
          code: 'custom',
          path: ['events', index, 'revision'],
          message: 'Replay event revisions must be contiguous',
        });
      }
      if (event.hostEpoch !== value.hostEpoch || event.sceneId !== value.sceneId) {
        context.addIssue({
          code: 'custom',
          path: ['events', index],
          message: 'Replay events must belong to the replay scene and host epoch',
        });
      }
    }
  });

export type StateReplayFrame = z.infer<typeof StateReplayFrameSchema>;

export const StateResyncRequiredFrameSchema = z.strictObject({
  t: z.literal('state.resyncRequired'),
  reason: z.enum(['retention-floor', 'epoch-changed', 'revision-gap', 'checksum', 'overflow']),
  hostEpoch: WorkspaceHostEpochSchema,
  sceneId: WorkspaceSceneIdSchema,
  currentRevision: WorkspaceRevisionSchema,
});

export type StateResyncRequiredFrame = z.infer<typeof StateResyncRequiredFrameSchema>;

export const StateIntentResultFrameSchema = z.discriminatedUnion('accepted', [
  z.strictObject({
    t: z.literal('state.intentResult'),
    operationId: boundedId,
    accepted: z.literal(true),
    committedRevision: positiveSafeInteger,
    result: JsonValueSchema.optional(),
  }),
  z.strictObject({
    t: z.literal('state.intentResult'),
    operationId: boundedId,
    accepted: z.literal(false),
    currentRevision: WorkspaceRevisionSchema,
    error: WorkspaceMirrorErrorSchema,
  }),
]);

export type StateIntentResultFrame = z.infer<typeof StateIntentResultFrameSchema>;

export const AuthChallengeFrameSchema = z.strictObject({
  t: z.literal('auth.challenge'),
  nonce: z.string().min(32).max(1024),
  expiresAt: timestamp,
});

export const AuthProofFrameSchema = z.strictObject({
  t: z.literal('auth.proof'),
  deviceId: boundedId,
  nonce: z.string().min(32).max(1024),
  signature: z.string().min(64).max(2048),
  publicKey: z
    .string()
    .min(40)
    .max(2048)
    .regex(/^[A-Za-z0-9+/]*={0,2}$/)
    .optional(),
});

export const ClientHelloFrameSchema = z.strictObject({
  t: z.literal('clientHello'),
  protocolVersions: z.array(positiveSafeInteger).min(1).max(16),
  schemaVersions: z.array(positiveSafeInteger).min(1).max(16),
  deviceId: boundedId,
  clientId: boundedId,
  capabilities: z.array(WorkspaceMirrorCapabilitySchema).max(64),
  resumeCursor: WorkspaceResumeCursorSchema.nullable(),
});

export const ServerHelloFrameSchema = z.strictObject({
  t: z.literal('serverHello'),
  protocolVersion: z.literal(WORKSPACE_MIRROR_PROTOCOL_VERSION),
  schemaVersion: z.literal(WORKSPACE_MIRROR_SCHEMA_VERSION),
  hostId: WorkspaceHostIdSchema,
  hostEpoch: WorkspaceHostEpochSchema,
  sceneId: WorkspaceSceneIdSchema,
  currentRevision: WorkspaceRevisionSchema,
  capabilities: z.array(WorkspaceMirrorCapabilitySchema).max(64),
  scopes: z.array(WorkspaceMirrorScopeSchema).max(2),
  bootstrapPhase: WorkspaceSyncPhaseSchema,
});

export type AuthChallengeFrame = z.infer<typeof AuthChallengeFrameSchema>;
export type AuthProofFrame = z.infer<typeof AuthProofFrameSchema>;
export type ClientHelloFrame = z.infer<typeof ClientHelloFrameSchema>;
export type ServerHelloFrame = z.infer<typeof ServerHelloFrameSchema>;

export const ControlRequestFrameSchema = z.strictObject({
  t: z.literal('control.request'),
  requestId: boundedId,
  knownCoordSeq: WorkspaceSequenceSchema,
});

export const ControlGrantedFrameSchema = z.strictObject({
  t: z.literal('control.granted'),
  coordSeq: positiveSafeInteger,
  lease: ControllerLeaseSchema,
});

export const ControlReleasedFrameSchema = z.strictObject({
  t: z.literal('control.released'),
  coordSeq: positiveSafeInteger,
  leaseId: boundedId,
  reason: z.enum(['released', 'disconnect-timeout', 'expired', 'shutdown']),
});

export const ControlRevokedFrameSchema = z.strictObject({
  t: z.literal('control.revoked'),
  coordSeq: positiveSafeInteger,
  leaseId: boundedId,
  reason: z.enum(['host-revoked', 'transferred', 'credential-revoked', 'expired']),
});

export const CoordinationPresenceFrameSchema = z.strictObject({
  t: z.literal('coord.presence'),
  coordSeq: positiveSafeInteger,
  clients: z
    .array(
      z.strictObject({
        clientId: boundedId,
        deviceId: boundedId,
        scopes: z.array(WorkspaceMirrorScopeSchema).max(2),
        phase: WorkspaceSyncPhaseSchema,
      })
    )
    .max(256),
});

export const CoordinationSyncFrameSchema = z.strictObject({
  t: z.literal('coord.sync'),
  coordSeq: positiveSafeInteger,
  clientId: boundedId,
  phase: WorkspaceSyncPhaseSchema,
});

export const WorkspaceCoordFrameSchema = z.discriminatedUnion('t', [
  ControlRequestFrameSchema,
  ControlGrantedFrameSchema,
  ControlReleasedFrameSchema,
  ControlRevokedFrameSchema,
  CoordinationPresenceFrameSchema,
  CoordinationSyncFrameSchema,
]);

export type WorkspaceCoordFrame = z.infer<typeof WorkspaceCoordFrameSchema>;

export const WorkspaceStreamKindSchema = z.enum(['terminal', 'agent']);
export type WorkspaceStreamKind = z.infer<typeof WorkspaceStreamKindSchema>;

const streamIdentity = {
  streamId: boundedId,
  streamKind: WorkspaceStreamKindSchema,
  entityId: boundedId,
  entityGeneration: positiveSafeInteger,
};

export const StreamAttachFrameSchema = z.strictObject({
  t: z.literal('stream.attach'),
  ...streamIdentity,
  sceneRevision: WorkspaceRevisionSchema,
  fromStreamSeq: WorkspaceSequenceSchema,
});

export const StreamAttachedFrameSchema = z.strictObject({
  t: z.literal('stream.attached'),
  ...streamIdentity,
  sceneRevision: WorkspaceRevisionSchema,
  reset: z.boolean(),
  retainedFromSeq: WorkspaceSequenceSchema,
  currentStreamSeq: WorkspaceSequenceSchema,
  replayedEventCount: WorkspaceSequenceSchema,
});

export const StreamChunkFrameSchema = z.strictObject({
  t: z.literal('stream.chunk'),
  ...streamIdentity,
  sceneRevision: WorkspaceRevisionSchema,
  streamSeq: positiveSafeInteger,
  encoding: z.enum(['utf8', 'base64']),
  data: z.string().max(maxEncodedSnapshotChunkLength),
});

export const StreamInputFrameSchema = z.strictObject({
  t: z.literal('stream.input'),
  ...streamIdentity,
  operationId: boundedId,
  data: z.string().max(1024 * 1024),
});

export const StreamResizeFrameSchema = z.strictObject({
  t: z.literal('stream.resize'),
  ...streamIdentity,
  operationId: boundedId,
  cols: z.number().int().min(1).max(1000),
  rows: z.number().int().min(1).max(1000),
});

export const StreamDetachFrameSchema = z.strictObject({
  t: z.literal('stream.detach'),
  ...streamIdentity,
});

export const StreamResetFrameSchema = z.strictObject({
  t: z.literal('stream.reset'),
  ...streamIdentity,
  reason: z.enum(['retention-overflow', 'entity-restarted', 'sequence-gap', 'authorization']),
  nextStreamSeq: WorkspaceSequenceSchema,
  sceneRevision: WorkspaceRevisionSchema,
});

export const StreamClosedFrameSchema = z.strictObject({
  t: z.literal('stream.closed'),
  ...streamIdentity,
  finalStreamSeq: WorkspaceSequenceSchema,
  reason: z.enum(['exited', 'closed', 'terminated', 'host-restart']),
  exitCode: z.number().int().nullable(),
});

export const WorkspaceStreamFrameSchema = z.discriminatedUnion('t', [
  StreamAttachFrameSchema,
  StreamAttachedFrameSchema,
  StreamChunkFrameSchema,
  StreamInputFrameSchema,
  StreamResizeFrameSchema,
  StreamDetachFrameSchema,
  StreamResetFrameSchema,
  StreamClosedFrameSchema,
]);

export type WorkspaceStreamFrame = z.infer<typeof WorkspaceStreamFrameSchema>;

export type StreamAttachFrame = z.infer<typeof StreamAttachFrameSchema>;
export type StreamAttachedFrame = z.infer<typeof StreamAttachedFrameSchema>;
export type StreamChunkFrame = z.infer<typeof StreamChunkFrameSchema>;
export type StreamInputFrame = z.infer<typeof StreamInputFrameSchema>;
export type StreamResizeFrame = z.infer<typeof StreamResizeFrameSchema>;
export type StreamDetachFrame = z.infer<typeof StreamDetachFrameSchema>;
export type StreamResetFrame = z.infer<typeof StreamResetFrameSchema>;
export type StreamClosedFrame = z.infer<typeof StreamClosedFrameSchema>;

export const WorkspaceMirrorErrorFrameSchema = z.strictObject({
  t: z.literal('error'),
  requestId: boundedId.optional(),
  error: WorkspaceMirrorErrorSchema,
});

export type WorkspaceMirrorErrorFrame = z.infer<typeof WorkspaceMirrorErrorFrameSchema>;

export const WorkspaceMirrorV2FrameSchema = z.union([
  AuthChallengeFrameSchema,
  AuthProofFrameSchema,
  ClientHelloFrameSchema,
  ServerHelloFrameSchema,
  ResourceUploadBeginFrameSchema,
  ResourceUploadChunkFrameSchema,
  ResourceUploadEndFrameSchema,
  ResourceUploadResultFrameSchema,
  StateSubscribeFrameSchema,
  StateSnapshotBeginFrameSchema,
  StateSnapshotChunkFrameSchema,
  StateSnapshotEndFrameSchema,
  WorkspaceSceneEventSchema,
  StateReplayFrameSchema,
  StateResyncRequiredFrameSchema,
  WorkspaceSceneIntentSchema,
  StateIntentResultFrameSchema,
  WorkspaceCoordFrameSchema,
  WorkspaceStreamFrameSchema,
  WorkspaceMirrorErrorFrameSchema,
]);

export type WorkspaceMirrorV2Frame = z.infer<typeof WorkspaceMirrorV2FrameSchema>;

function canonicalizeJsonValue(value: unknown, ancestors: Set<object>): string {
  if (value === null || typeof value === 'boolean' || typeof value === 'string') {
    return JSON.stringify(value);
  }
  if (typeof value === 'number') {
    if (!Number.isFinite(value)) {
      throw new TypeError('Canonical JSON cannot contain a non-finite number');
    }
    return JSON.stringify(value);
  }
  if (Array.isArray(value)) {
    if (ancestors.has(value)) {
      throw new TypeError('Canonical JSON cannot contain a cycle');
    }
    ancestors.add(value);
    const result = `[${value.map((item) => canonicalizeJsonValue(item, ancestors)).join(',')}]`;
    ancestors.delete(value);
    return result;
  }
  if (typeof value !== 'object') {
    throw new TypeError(`Canonical JSON cannot contain ${typeof value}`);
  }
  const prototype = Object.getPrototypeOf(value);
  if (prototype !== Object.prototype && prototype !== null) {
    throw new TypeError('Canonical JSON accepts only plain objects');
  }
  if (ancestors.has(value)) {
    throw new TypeError('Canonical JSON cannot contain a cycle');
  }
  ancestors.add(value);
  const record = value as Record<string, unknown>;
  const result = `{${Object.keys(record)
    .sort()
    .map((key) => `${JSON.stringify(key)}:${canonicalizeJsonValue(record[key], ancestors)}`)
    .join(',')}}`;
  ancestors.delete(value);
  return result;
}

export function canonicalJson(value: unknown): string {
  return canonicalizeJsonValue(value, new Set());
}

export type WorkspaceSceneDigestPayload = Pick<
  WorkspaceSceneSnapshot,
  | 'schemaVersion'
  | 'catalog'
  | 'navigation'
  | 'editors'
  | 'agents'
  | 'terminals'
  | 'todos'
  | 'selections'
  | 'resources'
>;

export function getWorkspaceSceneDigestPayload(
  scene: WorkspaceSceneSnapshot
): WorkspaceSceneDigestPayload {
  const parsed = WorkspaceSceneSnapshotSchema.parse(scene);
  return {
    schemaVersion: parsed.schemaVersion,
    catalog: parsed.catalog,
    navigation: parsed.navigation,
    editors: parsed.editors,
    agents: parsed.agents,
    terminals: parsed.terminals,
    todos: parsed.todos,
    selections: parsed.selections,
    resources: parsed.resources,
  };
}

export function canonicalizeWorkspaceScene(scene: WorkspaceSceneSnapshot): string {
  return canonicalJson(getWorkspaceSceneDigestPayload(scene));
}

export async function digestWorkspaceScene(scene: WorkspaceSceneSnapshot): Promise<string> {
  const bytes = new TextEncoder().encode(canonicalizeWorkspaceScene(scene));
  const digest = await globalThis.crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest), (byte) => byte.toString(16).padStart(2, '0')).join('');
}
